---
tagFormat: "${version}"
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: dev
    prerelease: true
plugins:
  - "semantic-release-gitmoji"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "🔖 Deploy new version to `${nextRelease.version}` [skip release]\n\n${nextRelease.notes}"
